sudo: false

language: java

jdk:
 - oraclejdk8
 - openjdk7
 - openjdk8

matrix:
  allow_failures:
  - jdk: openjdk7

before_install:
 - "export JAVA_OPTS=-Xmx1500m"
 - "echo JAVA_OPTS=$JAVA_OPTS"
 - "export MAVEN_OPTS=-Xmx1500m"
 - "echo MAVEN_OPTS=$MAVEN_OPTS"
 - "export _JAVA_OPTIONS=-Xmx1500m"
 - "echo _JAVA_OPTIONS=$_JAVA_OPTIONS"

cache:
  directories:
  - $HOME/.m2

script:
 - travis_wait 30 mvn install
 - cd contrib && mvn install

after_failure:
  - cat */target/surefire-reports/*.txt
